import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Send,
  Sparkles,
  CheckCircle,
  AlertCircle,
  ArrowLeft,
  Settings,
  Code2,
  Database,
  Clock,
  Paperclip,
} from "lucide-react";

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  summary?: string;
  explanation?: string;
  confidence?: number;
  timestamp: string;
}

interface LiveAssistantProps {
  assistantName: string;
  themeColor: string;
  tone: "formal" | "neutral" | "friendly";
  responseLength: number[];
  riskSensitivity: number[];
  onBack: () => void;
  onEditConfiguration: () => void;
  onOpenIntegration: () => void;
}

const suggestedQueries = [
  "Summarize this policy document",
  "What risks should we consider?",
  "Provide next best actions",
  "Explain the key terms",
  "Highlight compliance concerns",
];

const LiveAssistant = ({
  assistantName,
  themeColor,
  tone,
  responseLength,
  riskSensitivity,
  onBack,
  onEditConfiguration,
  onOpenIntegration,
}: LiveAssistantProps) => {
  const [query, setQuery] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const getLengthLabel = (value: number) => {
    if (value < 33) return "Short";
    if (value < 66) return "Standard";
    return "Detailed";
  };

  const getSensitivityLabel = (value: number) => {
    if (value < 33) return "Conservative";
    if (value < 66) return "Balanced";
    return "Aggressive";
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: "user",
      content: query,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMessage]);
    setQuery("");
    setIsLoading(true);

    setTimeout(() => {
      const assistantMessage: ChatMessage = {
        id: `asst-${Date.now()}`,
        role: "assistant",
        content:
          "Based on your connected data sources, here's a concise summary of the relevant information. The analysis draws from multiple documents to provide a comprehensive view.",
        summary:
          "The requested information has been identified across 3 knowledge sources with high relevance scores.",
        explanation:
          "This response was generated by analyzing 1,234 documents across your connected knowledge sources. Key factors include: document relevance scoring, cross-reference validation, and contextual analysis.",
        confidence: 87,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, assistantMessage]);
      setIsLoading(false);
    }, 1500);
  };

  return (
    <div className="p-8 flex flex-col min-h-screen">
      {/* Top Header */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between mb-6"
      >
        <div className="flex items-center gap-4">
          <button
            onClick={onBack}
            className="w-10 h-10 rounded-xl bg-secondary hover:bg-muted flex items-center justify-center transition-colors"
          >
            <ArrowLeft className="w-5 h-5 text-foreground" />
          </button>
          <div className="flex items-center gap-3">
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center text-white font-bold"
              style={{ backgroundColor: themeColor }}
            >
              {assistantName.charAt(0) || "A"}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-page-title">{assistantName || "Assistant"}</h1>
                <span className="status-pill status-active">Published</span>
                <span className="px-2.5 py-1 bg-secondary rounded-lg text-xs text-muted-foreground">
                  v1.0
                </span>
              </div>
              <p className="text-xs text-muted-foreground mt-0.5">
                Live production environment
              </p>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={onEditConfiguration}
            className="h-10 px-5 rounded-xl font-medium text-sm bg-secondary text-foreground hover:bg-muted transition-colors flex items-center gap-2"
          >
            <Settings className="w-4 h-4" />
            Edit Configuration
          </button>
          <motion.button
            onClick={onOpenIntegration}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            className="h-10 px-5 rounded-xl font-medium text-sm border-2 border-primary text-primary hover:bg-primary-subtle transition-colors flex items-center gap-2"
          >
            <Code2 className="w-4 h-4" />
            Integration & API
          </motion.button>
        </div>
      </motion.div>

      {/* Success Banner */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-6 px-5 py-3 bg-[hsl(142,71%,95%)] border border-[hsl(142,71%,85%)] rounded-xl flex items-center gap-3"
      >
        <CheckCircle className="w-5 h-5 text-[hsl(142,71%,35%)]" />
        <span className="text-sm text-[hsl(142,71%,25%)] font-medium">
          Your assistant is now live. You can test it here or integrate it into your applications.
        </span>
      </motion.div>

      {/* Main Two-Column Layout */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column — Live Chat */}
        <div className="lg:col-span-2">
          <div className="card-float flex flex-col h-[600px]">
            {/* Chat Header */}
            <div className="px-6 py-4 border-b border-border flex items-center gap-3">
              <div
                className="w-8 h-8 rounded-lg flex items-center justify-center text-white font-bold text-sm"
                style={{ backgroundColor: themeColor }}
              >
                {assistantName.charAt(0) || "A"}
              </div>
              <div>
                <div className="text-sm font-medium text-foreground">
                  {assistantName || "Assistant"}
                </div>
                <div className="text-xs text-muted-foreground">Online • Ready</div>
              </div>
            </div>

            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center h-full text-center">
                  <div
                    className="w-16 h-16 rounded-2xl flex items-center justify-center mb-4"
                    style={{ backgroundColor: `${themeColor}15` }}
                  >
                    <Sparkles className="w-8 h-8" style={{ color: themeColor }} />
                  </div>
                  <p className="text-sm text-muted-foreground mb-4">
                    Start a conversation to test the live experience
                  </p>
                  <div className="flex flex-wrap justify-center gap-2">
                    {suggestedQueries.slice(0, 3).map((q) => (
                      <button
                        key={q}
                        onClick={() => setQuery(q)}
                        className="px-3 py-1.5 bg-secondary hover:bg-primary-subtle text-xs text-foreground rounded-full transition-all"
                      >
                        {q}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {messages.map((msg) => (
                <motion.div
                  key={msg.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  {msg.role === "user" ? (
                    <div className="max-w-[70%]">
                      <div className="bg-primary text-primary-foreground px-4 py-3 rounded-2xl rounded-br-md text-sm">
                        {msg.content}
                      </div>
                      <div className="text-xs text-muted-foreground mt-1 text-right">
                        {msg.timestamp}
                      </div>
                    </div>
                  ) : (
                    <div className="max-w-[80%] flex gap-3">
                      <div
                        className="w-7 h-7 rounded-lg flex items-center justify-center text-white font-bold text-xs shrink-0 mt-1"
                        style={{ backgroundColor: themeColor }}
                      >
                        {assistantName.charAt(0) || "A"}
                      </div>
                      <div>
                        <div className="card-elevated p-4 !rounded-2xl !rounded-tl-md space-y-3">
                          <p className="text-sm text-foreground leading-relaxed">
                            {msg.content}
                          </p>
                          {msg.summary && (
                            <div className="bg-secondary rounded-lg p-3">
                              <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
                                Summary
                              </h4>
                              <p className="text-xs text-foreground">{msg.summary}</p>
                            </div>
                          )}
                          {msg.confidence && (
                            <div className="flex items-center gap-2">
                              {msg.confidence >= 80 ? (
                                <CheckCircle className="w-3.5 h-3.5 text-[hsl(var(--success))]" />
                              ) : (
                                <AlertCircle className="w-3.5 h-3.5 text-[hsl(var(--warning))]" />
                              )}
                              <span className="text-xs text-muted-foreground">
                                Confidence: {msg.confidence}%
                              </span>
                            </div>
                          )}
                        </div>
                        <div className="text-xs text-muted-foreground mt-1">
                          {msg.timestamp}
                        </div>
                      </div>
                    </div>
                  )}
                </motion.div>
              ))}

              <AnimatePresence>
                {isLoading && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    className="flex gap-3"
                  >
                    <div
                      className="w-7 h-7 rounded-lg flex items-center justify-center text-white font-bold text-xs shrink-0"
                      style={{ backgroundColor: themeColor }}
                    >
                      {assistantName.charAt(0) || "A"}
                    </div>
                    <div className="card-elevated px-4 py-3 !rounded-2xl !rounded-tl-md">
                      <div className="flex items-center gap-2">
                        <div className="flex gap-1">
                          <div className="w-2 h-2 bg-muted-foreground/40 rounded-full animate-bounce [animation-delay:0ms]" />
                          <div className="w-2 h-2 bg-muted-foreground/40 rounded-full animate-bounce [animation-delay:150ms]" />
                          <div className="w-2 h-2 bg-muted-foreground/40 rounded-full animate-bounce [animation-delay:300ms]" />
                        </div>
                        <span className="text-xs text-muted-foreground ml-2">Analyzing...</span>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Input Area */}
            <div className="px-6 py-4 border-t border-border">
              <form onSubmit={handleSubmit} className="relative flex items-center gap-2">
                <button
                  type="button"
                  className="w-10 h-10 rounded-xl bg-secondary hover:bg-muted flex items-center justify-center transition-colors shrink-0"
                >
                  <Paperclip className="w-4 h-4 text-muted-foreground" />
                </button>
                <input
                  type="text"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Ask a question in plain language..."
                  className="flex-1 h-11 pl-4 pr-4 bg-background border border-input rounded-xl text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring transition-all"
                />
                <button
                  type="submit"
                  disabled={!query.trim() || isLoading}
                  className="w-10 h-10 bg-primary hover:bg-primary-hover disabled:bg-muted text-primary-foreground disabled:text-muted-foreground rounded-xl flex items-center justify-center transition-all shrink-0"
                >
                  <Send className="w-4 h-4" />
                </button>
              </form>
            </div>
          </div>
        </div>

        {/* Right Column — Summary */}
        <div className="lg:col-span-1">
          <div className="card-float p-6 sticky top-8">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-5">
              Assistant Summary
            </h3>

            <div className="space-y-5">
              {/* Active Knowledge Sources */}
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Database className="w-4 h-4 text-primary" />
                  <span className="text-sm font-medium text-foreground">Knowledge Sources</span>
                </div>
                <div className="space-y-2">
                  {["SharePoint - Policies", "AWS S3 - Reports", "Uploaded Documents"].map(
                    (source) => (
                      <div
                        key={source}
                        className="flex items-center gap-2 px-3 py-2 bg-secondary rounded-lg"
                      >
                        <div className="w-1.5 h-1.5 rounded-full bg-[hsl(var(--success))]" />
                        <span className="text-xs text-foreground">{source}</span>
                      </div>
                    )
                  )}
                </div>
              </div>

              {/* Configuration */}
              <div className="space-y-3 pt-4 border-t border-border">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground">Tone</span>
                  <span className="text-xs font-medium text-foreground capitalize">{tone}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground">Response Length</span>
                  <span className="text-xs font-medium text-foreground">
                    {getLengthLabel(responseLength[0])}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground">Analysis Depth</span>
                  <span className="text-xs font-medium text-foreground">
                    {getSensitivityLabel(riskSensitivity[0])}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground">Theme</span>
                  <div className="flex items-center gap-2">
                    <div
                      className="w-4 h-4 rounded-md"
                      style={{ backgroundColor: themeColor }}
                    />
                    <span className="text-xs font-medium text-foreground">{themeColor}</span>
                  </div>
                </div>
              </div>

              {/* Last Published */}
              <div className="pt-4 border-t border-border">
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Clock className="w-3.5 h-3.5" />
                  Last published: Just now
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LiveAssistant;
