import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Send,
  Sparkles,
  CheckCircle,
  AlertCircle,
  ChevronRight,
} from "lucide-react";

interface QueryResponse {
  id: string;
  query: string;
  summary: string;
  explanation: string;
  confidence: number;
}

interface TestPublishStepProps {
  themeColor: string;
  assistantName: string;
  onBack: () => void;
  onPublish: () => void;
  isPublished: boolean;
  isPreviewOnly?: boolean;
}

const suggestedQueries = [
  "Summarize this document",
  "What risks should we consider?",
  "Provide next best actions",
  "Explain the key terms",
  "Highlight compliance concerns",
];

const TestPublishStep = ({
  themeColor,
  assistantName,
  onBack,
  onPublish,
  isPublished,
  isPreviewOnly,
}: TestPublishStepProps) => {
  const [query, setQuery] = useState("");
  const [responses, setResponses] = useState<QueryResponse[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsLoading(true);
    setTimeout(() => {
      const newResponse: QueryResponse = {
        id: Date.now().toString(),
        query: query,
        summary: "Based on your connected data sources, here's a concise summary of the relevant information. The analysis draws from multiple documents to provide a comprehensive view.",
        explanation: "This response was generated by analyzing 1,234 documents across your connected knowledge sources. Key factors include: document relevance scoring, cross-reference validation, and contextual analysis from historical data.",
        confidence: 87,
      };
      setResponses([newResponse, ...responses]);
      setQuery("");
      setIsLoading(false);
    }, 1500);
  };

  return (
    <div className="w-full max-w-[960px]">
      <div className="card-float p-8 mb-6">
        <h2 className="text-section-title mb-2">Preview Your Assistant</h2>
        <p className="text-muted-foreground text-sm mb-6">
          Ask a question to validate your configuration before proceeding.
        </p>

        <div className="flex flex-wrap gap-2 mb-6">
          {suggestedQueries.map((q) => (
            <button key={q} onClick={() => setQuery(q)} className="px-4 py-2 bg-secondary hover:bg-primary-subtle text-sm text-foreground rounded-full transition-all hover:scale-105">
              {q}
            </button>
          ))}
        </div>

        <form onSubmit={handleSubmit}>
          <div className="relative">
            <input type="text" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Ask a question in plain language" className="w-full h-14 pl-5 pr-14 bg-background border border-input rounded-xl text-foreground focus:outline-none focus:ring-2 focus:ring-ring transition-all" />
            <button type="submit" disabled={!query.trim() || isLoading} className="absolute right-2 top-1/2 -translate-y-1/2 w-10 h-10 bg-primary hover:bg-primary-hover disabled:bg-muted text-primary-foreground disabled:text-muted-foreground rounded-lg flex items-center justify-center transition-all hover:scale-105 disabled:hover:scale-100">
              <Send className="w-5 h-5" />
            </button>
          </div>
        </form>
      </div>

      <AnimatePresence>
        {isLoading && (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="card-elevated p-6 mb-6">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full flex items-center justify-center animate-pulse" style={{ backgroundColor: `${themeColor}20` }}>
                <Sparkles className="w-4 h-4" style={{ color: themeColor }} />
              </div>
              <span className="text-sm text-muted-foreground">Analyzing your data sources...</span>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="space-y-6 mb-8">
        {responses.map((response, index) => (
          <motion.div key={response.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.1 }} className="card-elevated p-6">
            <div className="flex items-start gap-3 mb-4 pb-4 border-b border-border">
              <div className="w-8 h-8 bg-muted rounded-full flex items-center justify-center shrink-0">
                <span className="text-xs font-medium text-muted-foreground">You</span>
              </div>
              <p className="text-sm text-foreground pt-1">{response.query}</p>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 rounded-full flex items-center justify-center shrink-0 text-white font-medium text-xs" style={{ backgroundColor: themeColor }}>
                {assistantName.charAt(0) || "A"}
              </div>
              <div className="flex-1 space-y-4">
                <div>
                  <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">Summary</h4>
                  <p className="text-sm text-foreground leading-relaxed">{response.summary}</p>
                </div>
                <div>
                  <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">Explanation</h4>
                  <p className="text-sm text-muted-foreground leading-relaxed">{response.explanation}</p>
                </div>
                <div className="flex items-center gap-2 pt-2">
                  {response.confidence >= 80 ? <CheckCircle className="w-4 h-4 text-success" /> : <AlertCircle className="w-4 h-4 text-warning" />}
                  <span className="text-xs text-muted-foreground">Confidence: {response.confidence}%</span>
                </div>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="flex items-center justify-between">
        <button onClick={onBack} className="h-11 px-5 rounded-xl font-medium text-sm bg-secondary text-foreground hover:bg-muted transition-colors">
          Back to Configure
        </button>
        <motion.button
          onClick={onPublish}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          className="h-12 px-8 rounded-xl font-medium text-sm flex items-center gap-2 bg-primary hover:bg-primary-hover text-primary-foreground shadow-lg shadow-primary/25 transition-all"
        >
          {isPreviewOnly ? (
            <>
              Continue to Assign
              <ChevronRight className="w-4 h-4" />
            </>
          ) : isPublished ? (
            <>
              <CheckCircle className="w-5 h-5" />
              Published Successfully!
            </>
          ) : (
            <>
              <Sparkles className="w-5 h-5" />
              Publish Assistant
            </>
          )}
        </motion.button>
      </div>
    </div>
  );
};

export default TestPublishStep;
